/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaassignment;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import main.FileReaderUtil;
import main.FileWriterUtil;

/**
 *
 * @author HP
 */
public class FinanceReport extends javax.swing.JFrame {

    /**
     * Creates new form FinanceReport
     */
    public FinanceReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportArea = new javax.swing.JTextArea();
        Generate_Report = new javax.swing.JButton();
        Export_File = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Finance Report");

        reportArea.setColumns(20);
        reportArea.setRows(5);
        jScrollPane1.setViewportView(reportArea);

        Generate_Report.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Generate_Report.setText("Generate Report");
        Generate_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_ReportActionPerformed(evt);
            }
        });

        Export_File.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Export_File.setText("Export File");
        Export_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export_FileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Generate_Report)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Export_File))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Generate_Report)
                    .addComponent(Export_File))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Generate_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_ReportActionPerformed
        List<String[]> items = FileReaderUtil.readFile("item.txt");
        List<String[]> sales = FileReaderUtil.readFile("sales_entry.txt");

        Map<String, String> itemNameMap = new HashMap<>();
        Map<String, Double> itemCostMap = new HashMap<>();

        for (String[] item : items) {
            if (item.length >= 5) {
                itemNameMap.put(item[0], item[1]); // itemCode -> itemName
                itemCostMap.put(item[0], Double.parseDouble(item[3])); // supplier price
            }
        }

        double totalRevenue = 0, totalCost = 0, totalProfit = 0;
        StringBuilder report = new StringBuilder();
        report.append("OWSB Finance Report\n");
        report.append("Generated on: " + new java.util.Date() + "\n\n");
        report.append(String.format("%-8s %-12s %-15s %-8s %-5s %-9s %-10s %-10s\n",
            "Sale ID", "Date", "Item", "Price", "Qty", "Discount", "Revenue", "Profit"));
        report.append("-------------------------------------------------------------------------------\n");

        for (String[] sale : sales) {
            if (sale.length >= 7) {
                String id = sale[0];
                String date = sale[1];
                String itemCode = sale[2];
                String itemName = itemNameMap.getOrDefault(itemCode, itemCode);
                double price = Double.parseDouble(sale[4]);
                int qty = Integer.parseInt(sale[5]);
                double discount = (sale.length >= 8) ? Double.parseDouble(sale[7]) : 0;
                double discountRate = discount / 100.0;

                double revenue = price * qty * (1 - discountRate);
                double cost = itemCostMap.getOrDefault(itemCode, 0.0) * qty;
                double profit = revenue - cost;

                totalRevenue += revenue;
                totalCost += cost;
                totalProfit += profit;

                report.append(String.format("%-8s %-12s %-15s %-8.2f %-5d %-9.2f %-10.2f %-10.2f\n",
                    id, date, itemName, price, qty, discount, revenue, profit));
            }
        }

        report.append("\nSummary:\n");
        report.append(String.format("Total Revenue: RM %.2f\n", totalRevenue));
        report.append(String.format("Total Cost:    RM %.2f\n", totalCost));
        report.append(String.format("Total Profit:  RM %.2f\n", totalProfit));

        // replace 'reportArea' with your actual JTextArea variable name
        reportArea.setText(report.toString());

    }//GEN-LAST:event_Generate_ReportActionPerformed

    private void Export_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export_FileActionPerformed
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("finance_report.txt"))) {
            writer.write(reportArea.getText());
            JOptionPane.showMessageDialog(this, "✅ Report exported to finance_report.txt");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "❌ Error writing report: " + e.getMessage());
        }

    }//GEN-LAST:event_Export_FileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Export_File;
    private javax.swing.JButton Generate_Report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reportArea;
    // End of variables declaration//GEN-END:variables
}
