/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financeManager;

import admin.LoginGUI;

/**
 *
 * @author HP
 */
public class FinanceManagerMenu extends javax.swing.JFrame {


    public FinanceManagerMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        jPanel1.setBackground(new java.awt.Color(0xc5e1ef));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        POApproval_Button = new javax.swing.JButton();
        FiananceReport_Button = new javax.swing.JButton();
        ProcessPayment_Button = new javax.swing.JButton();
        ViewPO_Button = new javax.swing.JButton();
        ViewPR_Button1 = new javax.swing.JButton();
        ViewPR_Button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Finance Manager Menu");

        POApproval_Button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        POApproval_Button.setText("PURCHASE ORDER APPROVAL");
        POApproval_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POApproval_ButtonActionPerformed(evt);
            }
        });

        FiananceReport_Button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FiananceReport_Button.setText("GENERATE FINANCE REPORT\n");
        FiananceReport_Button.setActionCommand("GENERATE FINANCE REPORT");
        FiananceReport_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiananceReport_ButtonActionPerformed(evt);
            }
        });

        ProcessPayment_Button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ProcessPayment_Button.setText("PROCESS PAYMENT");
        ProcessPayment_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessPayment_ButtonActionPerformed(evt);
            }
        });

        ViewPO_Button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ViewPO_Button.setText("VIEW PURCHASE ORDER");
        ViewPO_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPO_ButtonActionPerformed(evt);
            }
        });

        ViewPR_Button1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ViewPR_Button1.setText("VIEW PURCHASE REQUISITION\n");
        ViewPR_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPR_Button1ActionPerformed(evt);
            }
        });

        ViewPR_Button2.setBackground(new java.awt.Color(255, 102, 102));
        ViewPR_Button2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ViewPR_Button2.setText("LOG OUT");
        ViewPR_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPR_Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(POApproval_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FiananceReport_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProcessPayment_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewPO_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewPR_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewPR_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(POApproval_Button)
                .addGap(28, 28, 28)
                .addComponent(FiananceReport_Button)
                .addGap(26, 26, 26)
                .addComponent(ProcessPayment_Button)
                .addGap(31, 31, 31)
                .addComponent(ViewPO_Button)
                .addGap(29, 29, 29)
                .addComponent(ViewPR_Button1)
                .addGap(29, 29, 29)
                .addComponent(ViewPR_Button2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void POApproval_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POApproval_ButtonActionPerformed
        PurchaseOrderApproval poApprovalFrame = new PurchaseOrderApproval(); 
        poApprovalFrame.setVisible(true);                                        
        this.dispose();   
    }//GEN-LAST:event_POApproval_ButtonActionPerformed

    private void ProcessPayment_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessPayment_ButtonActionPerformed
        ProcessPaymentFrame paymentFrame = new ProcessPaymentFrame();
        paymentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProcessPayment_ButtonActionPerformed

    private void ViewPR_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPR_Button1ActionPerformed
        ViewPR ViewPRFrame = new ViewPR(); 
        ViewPRFrame.setVisible(true);                                        
        this.dispose();  
    }//GEN-LAST:event_ViewPR_Button1ActionPerformed

    private void ViewPO_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPO_ButtonActionPerformed
        ViewPOs ViewPOFrame = new ViewPOs(); 
        ViewPOFrame.setVisible(true);                                        
        this.dispose();  
    }//GEN-LAST:event_ViewPO_ButtonActionPerformed

    private void FiananceReport_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiananceReport_ButtonActionPerformed
        FinanceReport reportFrame = new FinanceReport();
        reportFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FiananceReport_ButtonActionPerformed

    private void ViewPR_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPR_Button2ActionPerformed
        // TODO add your handling code here:
        dispose(); 
        new LoginGUI().setVisible(true);
    }//GEN-LAST:event_ViewPR_Button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FiananceReport_Button;
    private javax.swing.JButton POApproval_Button;
    private javax.swing.JButton ProcessPayment_Button;
    private javax.swing.JButton ViewPO_Button;
    private javax.swing.JButton ViewPR_Button1;
    private javax.swing.JButton ViewPR_Button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
