/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financeManager;

import main.FileReaderUtil;
import main.FileWriterUtil;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.event.*;
import java.io.*;
import java.time.LocalDate;
import java.util.List;

/**
 *
 * @author HP
 */

public class ProcessPaymentGUI extends javax.swing.JFrame {

    public ProcessPaymentGUI() {
        initComponents();
        setupListeners();
        refreshButtonActionPerformed(null);
        poIDField.setEditable(false);
        pmIDField.setEditable(false);
        supplierIDField.setEditable(false);
        prIDField.setEditable(false);
        statusField.setEditable(false);
        itemCodeField.setEditable(false);
        quantityField.setEditable(false);
        unitPriceField.setEditable(false);
        totalPriceField.setEditable(false);
        paymentDateField.setEditable(false);
    }

    
    
    private void setupListeners() {
        poTable.getSelectionModel().addListSelectionListener(e -> {
            int row = poTable.getSelectedRow();
            if (row >= 0) {
                poIDField.setText(poTable.getValueAt(row, 0).toString());       // PO ID
                prIDField.setText(poTable.getValueAt(row, 1).toString());       // PR ID
                itemCodeField.setText(poTable.getValueAt(row, 2).toString());   // Item Code
                quantityField.setText(poTable.getValueAt(row, 3).toString());   // Quantity
                supplierIDField.setText(poTable.getValueAt(row, 6).toString()); // Supplier ID
                pmIDField.setText(poTable.getValueAt(row, 7).toString());       // PM ID
                statusField.setText(poTable.getValueAt(row, 9).toString());     // Status
                String unitPrice = poTable.getValueAt(row, 4).toString();
                String totalPrice = poTable.getValueAt(row, 5).toString();
                // Clear calculated fields and set today’s date
                unitPriceField.setText(unitPrice);
                totalPriceField.setText(totalPrice);
                paymentDateField.setText(java.time.LocalDate.now().toString());
            }
        });
    }



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Quantity_TextField = new javax.swing.JTextField();
        Item_Name_TextField = new javax.swing.JTextField();
        Supplier_TextField = new javax.swing.JTextField();
        Process_Payment_button = new javax.swing.JButton();
        PO_Title1 = new javax.swing.JPanel();
        PO_name1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PO_ID = new javax.swing.JLabel();
        Item_Name = new javax.swing.JLabel();
        Supplier = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        PO_ID_TextField = new javax.swing.JTextField();
        Status_TextField = new javax.swing.JTextField();
        Unit_Price = new javax.swing.JLabel();
        Total_Price = new javax.swing.JLabel();
        Unit_Price_TextField = new javax.swing.JTextField();
        Total_Price_TextField = new javax.swing.JTextField();
        Payment_Date = new javax.swing.JLabel();
        Payment_Date_TextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        processButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        poTable = new javax.swing.JTable();
        ItemCode_Label = new javax.swing.JLabel();
        itemCodeField = new javax.swing.JTextField();
        supplierIDField = new javax.swing.JTextField();
        PM_ID = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        PO_ID2 = new javax.swing.JLabel();
        prIDField = new javax.swing.JTextField();
        PaymentDate = new javax.swing.JLabel();
        PR_ID = new javax.swing.JLabel();
        paymentDateField = new javax.swing.JTextField();
        pmIDField = new javax.swing.JTextField();
        Supplier2 = new javax.swing.JLabel();
        Quantity2 = new javax.swing.JLabel();
        Status2 = new javax.swing.JLabel();
        poIDField = new javax.swing.JTextField();
        statusField = new javax.swing.JTextField();
        UnitPrice = new javax.swing.JLabel();
        unitPriceField = new javax.swing.JTextField();
        UnitPrice1 = new javax.swing.JLabel();
        totalPriceField = new javax.swing.JTextField();
        Search_TextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(213, 243, 243));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        Quantity_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quantity_TextFieldActionPerformed(evt);
            }
        });

        Item_Name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Name_TextFieldActionPerformed(evt);
            }
        });

        Supplier_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_TextFieldActionPerformed(evt);
            }
        });

        Process_Payment_button.setText("Process Payment");
        Process_Payment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Process_Payment_buttonActionPerformed(evt);
            }
        });

        PO_Title1.setBackground(new java.awt.Color(124, 203, 207));

        PO_name1.setBackground(new java.awt.Color(204, 204, 255));
        PO_name1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PO_name1.setText("Process Payment");

        javax.swing.GroupLayout PO_Title1Layout = new javax.swing.GroupLayout(PO_Title1);
        PO_Title1.setLayout(PO_Title1Layout);
        PO_Title1Layout.setHorizontalGroup(
            PO_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PO_Title1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(PO_name1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PO_Title1Layout.setVerticalGroup(
            PO_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PO_Title1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PO_name1)
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        PO_ID.setText("PO ID:");

        Item_Name.setText("Item Name:");

        Supplier.setText("Supplier:");

        Quantity.setText("Quantity:");

        Status.setText("Status:");

        PO_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_ID_TextFieldActionPerformed(evt);
            }
        });

        Status_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status_TextFieldActionPerformed(evt);
            }
        });

        Unit_Price.setText("Unit Price");

        Total_Price.setText("Total Price:");

        Unit_Price_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Unit_Price_TextFieldActionPerformed(evt);
            }
        });

        Total_Price_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_Price_TextFieldActionPerformed(evt);
            }
        });

        Payment_Date.setText("Payment Date:");

        Payment_Date_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Payment_Date_TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PO_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Payment_Date)
                                .addGap(18, 18, 18)
                                .addComponent(Payment_Date_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PO_ID)
                                    .addComponent(Item_Name)
                                    .addComponent(Quantity)
                                    .addComponent(Supplier)
                                    .addComponent(Status)
                                    .addComponent(Unit_Price)
                                    .addComponent(Total_Price))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Item_Name_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(Quantity_TextField)
                                    .addComponent(Supplier_TextField)
                                    .addComponent(Status_TextField)
                                    .addComponent(Unit_Price_TextField)
                                    .addComponent(Total_Price_TextField)
                                    .addComponent(PO_ID_TextField))))
                        .addGap(49, 49, 49)
                        .addComponent(Process_Payment_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PO_Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PO_ID)
                    .addComponent(PO_ID_TextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item_Name)
                    .addComponent(Item_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantity)
                            .addComponent(Quantity_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Supplier)
                            .addComponent(Supplier_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Process_Payment_button)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status)
                    .addComponent(Status_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Unit_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Unit_Price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Total_Price)
                    .addComponent(Total_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Payment_Date)
                    .addComponent(Payment_Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        processButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        processButton.setText("Process Payment");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        poTable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        poTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PO ID", "PR ID", "Item Code", "Quantity", "Unit Price", "Total Price", "Supplier ID", "PM ID", "Date", "Status"
            }
        ));
        jScrollPane5.setViewportView(poTable);

        ItemCode_Label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ItemCode_Label.setText("Item Code:");

        itemCodeField.setColumns(15);
        itemCodeField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        itemCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeFieldActionPerformed(evt);
            }
        });

        supplierIDField.setColumns(15);
        supplierIDField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        supplierIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierIDFieldActionPerformed(evt);
            }
        });

        PM_ID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PM_ID.setText("PM ID:");

        quantityField.setColumns(15);
        quantityField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        PO_ID2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PO_ID2.setText("PO ID:");

        prIDField.setColumns(15);
        prIDField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        prIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prIDFieldActionPerformed(evt);
            }
        });

        PaymentDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PaymentDate.setText("Payment Date:");

        PR_ID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PR_ID.setText("PR ID:");

        paymentDateField.setColumns(15);
        paymentDateField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        paymentDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentDateFieldActionPerformed(evt);
            }
        });

        pmIDField.setColumns(15);
        pmIDField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pmIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmIDFieldActionPerformed(evt);
            }
        });

        Supplier2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Supplier2.setText("Supplier ID:");

        Quantity2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Quantity2.setText("Quantity:");

        Status2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Status2.setText("Status:");

        poIDField.setColumns(15);
        poIDField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        poIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poIDFieldActionPerformed(evt);
            }
        });

        statusField.setColumns(15);
        statusField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        UnitPrice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UnitPrice.setText("Unit Price:");

        unitPriceField.setColumns(15);
        unitPriceField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        unitPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitPriceFieldActionPerformed(evt);
            }
        });

        UnitPrice1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UnitPrice1.setText("Total Price:");

        totalPriceField.setColumns(15);
        totalPriceField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceFieldActionPerformed(evt);
            }
        });

        Search_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Search_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_TextFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Process Payment");

        menuButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(processButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Supplier2)
                                        .addComponent(Status2)
                                        .addComponent(PR_ID)
                                        .addComponent(PO_ID2)
                                        .addComponent(PM_ID))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(prIDField)
                                        .addComponent(poIDField)
                                        .addComponent(supplierIDField)
                                        .addComponent(pmIDField)
                                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(376, 376, 376)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(UnitPrice)
                                                .addGap(10, 10, 10))
                                            .addComponent(UnitPrice1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Quantity2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ItemCode_Label, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(PaymentDate))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(itemCodeField)
                                        .addComponent(quantityField)
                                        .addComponent(unitPriceField)
                                        .addComponent(totalPriceField)
                                        .addComponent(paymentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Search_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(menuButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemCode_Label)
                            .addComponent(itemCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantity2)
                            .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UnitPrice)
                            .addComponent(unitPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UnitPrice1)
                            .addComponent(totalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PaymentDate)
                            .addComponent(paymentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PO_ID2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PR_ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplierIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PM_ID)
                            .addComponent(pmIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Status2))))
                .addGap(18, 18, 18)
                .addComponent(processButton)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Quantity_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quantity_TextFieldActionPerformed

    }//GEN-LAST:event_Quantity_TextFieldActionPerformed

    private void Item_Name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_Name_TextFieldActionPerformed

    private void Supplier_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_TextFieldActionPerformed

    }//GEN-LAST:event_Supplier_TextFieldActionPerformed

    private void Process_Payment_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Process_Payment_buttonActionPerformed

    }//GEN-LAST:event_Process_Payment_buttonActionPerformed

    private void PO_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_ID_TextFieldActionPerformed

    }//GEN-LAST:event_PO_ID_TextFieldActionPerformed

    private void Status_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status_TextFieldActionPerformed

    }//GEN-LAST:event_Status_TextFieldActionPerformed

    private void Unit_Price_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Unit_Price_TextFieldActionPerformed

    }//GEN-LAST:event_Unit_Price_TextFieldActionPerformed

    private void Total_Price_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_Price_TextFieldActionPerformed

    }//GEN-LAST:event_Total_Price_TextFieldActionPerformed

    private void Payment_Date_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Payment_Date_TextFieldActionPerformed

    }//GEN-LAST:event_Payment_Date_TextFieldActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        try {
            String poID = poIDField.getText().trim();
            String itemCode = itemCodeField.getText().trim();
            int quantity = Integer.parseInt(quantityField.getText().trim());
            String supplierID = supplierIDField.getText().trim();
            String paymentDate = paymentDateField.getText().trim();

            List<String[]> payments = FileReaderUtil.readFile("payments.txt");
            for (String[] p : payments) {
                if (p.length > 0 && p[0].equals(poID)) {
                    JOptionPane.showMessageDialog(this, "⚠ This PO has already been paid.");
                    return;
                }
            }

            List<String[]> items = FileReaderUtil.readFile("item.txt");
            double unitPrice = -1;
            for (String[] item : items) {
                if (item[0].equalsIgnoreCase(itemCode) && item[2].contains(supplierID)) {
                    unitPrice = Double.parseDouble(item[3]); // supplier price
                    break;
                }
            }

            if (unitPrice == -1) {
                JOptionPane.showMessageDialog(this, "❌ Supplier price not found for item.");
                return;
            }

            double totalPrice = unitPrice * quantity;

            String[] newPayment = {
                poID, supplierID, itemCode, String.valueOf(quantity),
                String.valueOf(unitPrice), String.valueOf(totalPrice), paymentDate
            };
            FileWriterUtil.appendToFile("payments.txt", String.join(",", newPayment));

            JOptionPane.showMessageDialog(this, "✅ Payment recorded: RM " + totalPrice);



        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error processing payment: " + e.getMessage());
        }
    }//GEN-LAST:event_processButtonActionPerformed

    private void itemCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeFieldActionPerformed
        itemCodeField.setEditable(false);
    }//GEN-LAST:event_itemCodeFieldActionPerformed

    private void supplierIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierIDFieldActionPerformed
        supplierIDField.setEditable(false);
    }//GEN-LAST:event_supplierIDFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        Quantity_TextField.setEditable(false);
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void prIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prIDFieldActionPerformed
        prIDField.setEditable(false);
    }//GEN-LAST:event_prIDFieldActionPerformed

    private void paymentDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentDateFieldActionPerformed
        paymentDateField.setEditable(false);
    }//GEN-LAST:event_paymentDateFieldActionPerformed

    private void pmIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmIDFieldActionPerformed
        pmIDField.setEditable(false);
    }//GEN-LAST:event_pmIDFieldActionPerformed

    private void poIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poIDFieldActionPerformed
        poIDField.setEditable(false);
    }//GEN-LAST:event_poIDFieldActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        statusField.setEditable(false);
    }//GEN-LAST:event_statusFieldActionPerformed

    private void unitPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitPriceFieldActionPerformed
        unitPriceField.setEditable(false);
    }//GEN-LAST:event_unitPriceFieldActionPerformed

    private void totalPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceFieldActionPerformed
        totalPriceField.setEditable(false);
    }//GEN-LAST:event_totalPriceFieldActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) poTable.getModel();
        model.setRowCount(0);

        try (BufferedReader br = new BufferedReader(new FileReader("purchase_orders.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 8 && parts[7].equalsIgnoreCase("Approved")) {
                    String poID = parts[0];
                    String prID = parts[1];
                    String itemCode = parts[2];
                    int quantity = Integer.parseInt(parts[3]);
                    String supplierID = parts[4];
                    String pmID = parts[5];
                    String date = parts[6];
                    String status = parts[7];

                    double unitPrice = Payment.lookupSupplierPrice(itemCode, supplierID, "item.txt");
                    double totalPrice = unitPrice * quantity;

                    model.addRow(new Object[]{
                        poID, prID, itemCode, quantity,
                        String.format("%.2f", unitPrice),
                        String.format("%.2f", totalPrice),
                        supplierID, pmID, date, status
                    });
                }
            }
            JOptionPane.showMessageDialog(this, "Refresh successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading data.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

    }//GEN-LAST:event_searchButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        FinanceManagerMenu menu = new FinanceManagerMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void Search_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcessPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcessPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcessPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcessPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessPaymentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ItemCode_Label;
    private javax.swing.JLabel Item_Name;
    private javax.swing.JTextField Item_Name_TextField;
    private javax.swing.JLabel PM_ID;
    private javax.swing.JLabel PO_ID;
    private javax.swing.JLabel PO_ID2;
    private javax.swing.JTextField PO_ID_TextField;
    private javax.swing.JPanel PO_Title1;
    private javax.swing.JLabel PO_name1;
    private javax.swing.JLabel PR_ID;
    private javax.swing.JLabel PaymentDate;
    private javax.swing.JLabel Payment_Date;
    private javax.swing.JTextField Payment_Date_TextField;
    private javax.swing.JButton Process_Payment_button;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel Quantity2;
    private javax.swing.JTextField Quantity_TextField;
    private javax.swing.JTextField Search_TextField;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Status2;
    private javax.swing.JTextField Status_TextField;
    private javax.swing.JLabel Supplier;
    private javax.swing.JLabel Supplier2;
    private javax.swing.JTextField Supplier_TextField;
    private javax.swing.JLabel Total_Price;
    private javax.swing.JTextField Total_Price_TextField;
    private javax.swing.JLabel UnitPrice;
    private javax.swing.JLabel UnitPrice1;
    private javax.swing.JLabel Unit_Price;
    private javax.swing.JTextField Unit_Price_TextField;
    private javax.swing.JTextField itemCodeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton menuButton;
    private javax.swing.JTextField paymentDateField;
    private javax.swing.JTextField pmIDField;
    private javax.swing.JTextField poIDField;
    private javax.swing.JTable poTable;
    private javax.swing.JTextField prIDField;
    private javax.swing.JButton processButton;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextField supplierIDField;
    private javax.swing.JTextField totalPriceField;
    private javax.swing.JTextField unitPriceField;
    // End of variables declaration//GEN-END:variables
}
