/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financeManager;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


/**
 *
 * @author HP
 */
public class PurchaseOrder_Approval extends javax.swing.JFrame {

    private ArrayList<PurchaseOrder> poList;
    private DefaultTableModel tableModel;
    

    /**
     * Creates new form PurchaseOrder_Approval
     */
    public PurchaseOrder_Approval() {
        initComponents();
        setLocationRelativeTo(null);
        loadTableData();
        setupListeners();
    }
    
    private void loadTableData() {
        poList = PurchaseOrder.loadPurchaseOrders();
        tableModel = new DefaultTableModel(new String[]{"PO ID", "PR ID", "Item Code", "Quantity", "Supplier ID", "PM ID", "Date", "Status"}, 0);
        jTable2.setModel(tableModel);
        for (PurchaseOrder po : poList) {
            tableModel.addRow(new Object[]{
                po.getPoID(),
                po.getPrID(),
                po.getItemCode(),
                po.getQuantity(),
                po.getSupplierID(),
                po.getPmID(),
                po.getDate(),
                po.getStatus()
            });
        }
    }
    
    private void setupListeners() {
        jTable2.getSelectionModel().addListSelectionListener(e -> {
            int row = jTable2.getSelectedRow();
            if (row >= 0 && row < jTable2.getRowCount()) {
                PurchaseOrder selectedPO = poList.get(row);
                PO_ID_TextField.setText(selectedPO.getPoID());
                PR_ID_TextField.setText(selectedPO.getPrID());
                Item_Code_TextField.setText(selectedPO.getItemCode());
                Quantity_TextField.setText(String.valueOf(selectedPO.getQuantity()));
                Supplier_ID_TextField.setText(selectedPO.getSupplierID());
                PM_ID_TextField.setText(selectedPO.getPmID());
                Date_TextField.setText(selectedPO.getDate());
                Status_TextField.setText(selectedPO.getStatus());
                
                PO_ID_TextField.setEditable(false);
                PR_ID_TextField.setEditable(false);
                Item_Code_TextField.setEditable(false);
                Quantity_TextField.setEditable(false);
                Supplier_ID_TextField.setEditable(false);
                PM_ID_TextField.setEditable(false);
                Date_TextField.setEditable(false);
                Status_TextField.setEditable(false);
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Quantity_TextField = new javax.swing.JTextField();
        PR_ID_TextField = new javax.swing.JTextField();
        PM_ID_TextField = new javax.swing.JTextField();
        Approve = new javax.swing.JButton();
        Modify_Quantity = new javax.swing.JButton();
        Change_Supplier = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        PO_Title1 = new javax.swing.JPanel();
        MenuButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PO_ID = new javax.swing.JLabel();
        PR_ID = new javax.swing.JLabel();
        Supplier = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        PO_ID_TextField = new javax.swing.JTextField();
        Status_TextField = new javax.swing.JTextField();
        ItemCode_Label = new javax.swing.JLabel();
        Item_Code_TextField = new javax.swing.JTextField();
        Supplier_ID_TextField = new javax.swing.JTextField();
        PM_ID = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Date_TextField = new javax.swing.JTextField();
        Search_TextField = new javax.swing.JTextField();
        RefreshButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        PO_name1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton1");

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        Quantity_TextField.setColumns(15);
        Quantity_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Quantity_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quantity_TextFieldActionPerformed(evt);
            }
        });

        PR_ID_TextField.setColumns(15);
        PR_ID_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PR_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR_ID_TextFieldActionPerformed(evt);
            }
        });

        PM_ID_TextField.setColumns(15);
        PM_ID_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PM_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PM_ID_TextFieldActionPerformed(evt);
            }
        });

        Approve.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Approve.setText("Approve");
        Approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveActionPerformed(evt);
            }
        });

        Modify_Quantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Modify_Quantity.setText("Modify Quantity");
        Modify_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify_QuantityActionPerformed(evt);
            }
        });

        Change_Supplier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Change_Supplier.setText("Change Supplier");
        Change_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change_SupplierActionPerformed(evt);
            }
        });

        Save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        PO_Title1.setBackground(java.awt.SystemColor.controlHighlight);

        MenuButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PO_Title1Layout = new javax.swing.GroupLayout(PO_Title1);
        PO_Title1.setLayout(PO_Title1Layout);
        PO_Title1Layout.setHorizontalGroup(
            PO_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PO_Title1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PO_Title1Layout.setVerticalGroup(
            PO_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PO_Title1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        PO_ID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PO_ID.setText("PO ID:");

        PR_ID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PR_ID.setText("PR ID:");

        Supplier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Supplier.setText("Supplier ID:");

        Quantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Quantity.setText("Quantity:");

        Status.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Status.setText("Status:");

        PO_ID_TextField.setColumns(15);
        PO_ID_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PO_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_ID_TextFieldActionPerformed(evt);
            }
        });

        Status_TextField.setColumns(15);
        Status_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Status_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status_TextFieldActionPerformed(evt);
            }
        });

        ItemCode_Label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ItemCode_Label.setText("Item Code:");

        Item_Code_TextField.setColumns(15);
        Item_Code_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Item_Code_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Code_TextFieldActionPerformed(evt);
            }
        });

        Supplier_ID_TextField.setColumns(15);
        Supplier_ID_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Supplier_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_ID_TextFieldActionPerformed(evt);
            }
        });

        PM_ID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PM_ID.setText("PM ID:");

        Date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Date.setText("Date:");

        Date_TextField.setColumns(15);
        Date_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Date_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_TextFieldActionPerformed(evt);
            }
        });

        Search_TextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        RefreshButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        SearchButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        PO_name1.setBackground(new java.awt.Color(204, 204, 255));
        PO_name1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        PO_name1.setText("Purchase Order Approval");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PO_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(PO_name1)
                .addGap(478, 478, 478))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RefreshButton)
                        .addGap(301, 301, 301)
                        .addComponent(Search_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quantity)
                            .addComponent(Supplier)
                            .addComponent(PR_ID)
                            .addComponent(PO_ID)
                            .addComponent(ItemCode_Label))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Supplier_ID_TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quantity_TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Item_Code_TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PR_ID_TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PO_ID_TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Status)
                                    .addComponent(PM_ID)
                                    .addComponent(Date))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PM_ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Status_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Modify_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Change_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(Approve, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PO_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(PO_name1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefreshButton)
                    .addComponent(Search_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PO_ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PO_ID))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PR_ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PR_ID)
                            .addComponent(Status))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Item_Code_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemCode_Label)
                            .addComponent(Date)
                            .addComponent(Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PM_ID)
                            .addComponent(PM_ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Status_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity)
                    .addComponent(Modify_Quantity))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Supplier))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Supplier_ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Change_Supplier)
                            .addComponent(Approve)
                            .addComponent(Save))))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Quantity_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quantity_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quantity_TextFieldActionPerformed

    private void PR_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR_ID_TextFieldActionPerformed

    private void PM_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PM_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PM_ID_TextFieldActionPerformed

    private void ApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveActionPerformed
        Status_TextField.setText("Approved");
    }//GEN-LAST:event_ApproveActionPerformed

    private void Modify_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify_QuantityActionPerformed
        Quantity_TextField.setEditable(true);
    }//GEN-LAST:event_Modify_QuantityActionPerformed

    private void Change_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change_SupplierActionPerformed
        Supplier_ID_TextField.setEditable(true);
    }//GEN-LAST:event_Change_SupplierActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        int row = jTable2.getSelectedRow();
        if (row >= 0) {
            PurchaseOrder selectedPO = poList.get(row);
            // Update PO details from TextFields
            selectedPO.setQuantity(Integer.parseInt(Quantity_TextField.getText()));
            selectedPO.setSupplierID(Supplier_ID_TextField.getText());
            selectedPO.setStatus(Status_TextField.getText());
            PurchaseOrder.savePurchaseOrders(poList);

            // Refresh table row
            tableModel.setValueAt(selectedPO.getQuantity(), row, 3);
            tableModel.setValueAt(selectedPO.getSupplierID(), row, 4);
            tableModel.setValueAt(selectedPO.getStatus(), row, 7);

            // Lock fields again
            Quantity_TextField.setEditable(false);
            Supplier_ID_TextField.setEditable(false);
            Status_TextField.setEditable(false);

            JOptionPane.showMessageDialog(this, "Changes saved for PO " + selectedPO.getPoID());
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void PO_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PO_ID_TextFieldActionPerformed

    private void Status_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Status_TextFieldActionPerformed

    private void Item_Code_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Code_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_Code_TextFieldActionPerformed

    private void Supplier_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Supplier_ID_TextFieldActionPerformed

    private void Date_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_TextFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String searchText = Search_TextField.getText().trim();
        tableModel.setRowCount(0);  // Clear table

        for (PurchaseOrder po : poList) {
            if (po.getPoID().contains(searchText)) {  // Filter by PO ID
                tableModel.addRow(new Object[]{
                    po.getPoID(),
                    po.getPrID(),
                    po.getItemCode(),
                    po.getQuantity(),
                    po.getSupplierID(),
                    po.getPmID(),
                    po.getDate(),
                    po.getStatus()
                });
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        FinanceManagerMenu menu = new FinanceManagerMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        loadTableData();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseOrder_Approval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approve;
    private javax.swing.JButton Change_Supplier;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField Date_TextField;
    private javax.swing.JLabel ItemCode_Label;
    private javax.swing.JTextField Item_Code_TextField;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton Modify_Quantity;
    private javax.swing.JLabel PM_ID;
    private javax.swing.JTextField PM_ID_TextField;
    private javax.swing.JLabel PO_ID;
    private javax.swing.JTextField PO_ID_TextField;
    private javax.swing.JPanel PO_Title1;
    private javax.swing.JLabel PO_name1;
    private javax.swing.JLabel PR_ID;
    private javax.swing.JTextField PR_ID_TextField;
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField Quantity_TextField;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton Save;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField Search_TextField;
    private javax.swing.JLabel Status;
    private javax.swing.JTextField Status_TextField;
    private javax.swing.JLabel Supplier;
    private javax.swing.JTextField Supplier_ID_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
