/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inventory;

/**
 *
 * @author limsh
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Inventory Manager Dashboard");
        getContentPane().setBackground(new java.awt.Color(0xc5e1ef));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        ViewItemsButton = new javax.swing.JButton();
        ViewPOsButton = new javax.swing.JButton();
        UpdateStockButton = new javax.swing.JButton();
        GenerateReportButton = new javax.swing.JButton();
        StockAlertsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Inventory Manager Dashboard");

        ViewItemsButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ViewItemsButton.setText("VIEW ITEMS");
        ViewItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewItemsButtonActionPerformed(evt);
            }
        });

        ViewPOsButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ViewPOsButton.setText("VIEW PURCHASE ORDERS");
        ViewPOsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPOsButtonActionPerformed(evt);
            }
        });

        UpdateStockButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UpdateStockButton.setText("UPDATE SROCK");
        UpdateStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStockButtonActionPerformed(evt);
            }
        });

        GenerateReportButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        GenerateReportButton.setText("GENERATE REPORT");
        GenerateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportButtonActionPerformed(evt);
            }
        });

        StockAlertsButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        StockAlertsButton.setText("STOCK ALERTS");
        StockAlertsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockAlertsButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LogoutButton.setText("LOGOUT");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ViewPOsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewItemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GenerateReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StockAlertsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(36, 36, 36)
                .addComponent(ViewItemsButton)
                .addGap(18, 18, 18)
                .addComponent(ViewPOsButton)
                .addGap(18, 18, 18)
                .addComponent(UpdateStockButton)
                .addGap(18, 18, 18)
                .addComponent(StockAlertsButton)
                .addGap(18, 18, 18)
                .addComponent(GenerateReportButton)
                .addGap(18, 18, 18)
                .addComponent(LogoutButton)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                         

    private void StockAlertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockAlertsButtonActionPerformed
        new StockAlerts().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_StockAlertsButtonActionPerformed

    private void ViewItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewItemsButtonActionPerformed
        new ViewItems().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ViewItemsButtonActionPerformed

    private void ViewPOsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPOsButtonActionPerformed
        new ViewPOs().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ViewPOsButtonActionPerformed

    private void UpdateStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStockButtonActionPerformed
        new UpdateStock().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_UpdateStockButtonActionPerformed

    private void GenerateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportButtonActionPerformed
        new GenerateReport().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_GenerateReportButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateReportButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton StockAlertsButton;
    private javax.swing.JLabel Title;
    private javax.swing.JButton UpdateStockButton;
    private javax.swing.JButton ViewItemsButton;
    private javax.swing.JButton ViewPOsButton;
    // End of variables declaration//GEN-END:variables
}
