/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaassignment;
import java.awt.*;
import java.util.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author User
 */
public class ItemManagement extends javax.swing.JFrame {
    List<Supplier> supplierList = new ArrayList<>();
    List<Item> itemList = new ArrayList<>();
    public ItemManagement() {
        initComponents();
        setLocationRelativeTo(null);
        
        supplierList = Supplier.loadSupplierFromFile("suppliers.txt");
        itemList = Item.loadItemFromFile("item.txt",supplierList);
        
        makeTableReadOnly();
        loadItemtoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BackToMenuBtn = new java.awt.Button();
        txtSalesPrice = new javax.swing.JTextField();
        txtItemPrice = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtItemId = new javax.swing.JTextField();
        selectSupplierbtn = new javax.swing.JButton();
        txtSupplierid = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(242, 242, 242));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITEM MANAGEMENT");

        ItemTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Supplier ID", "Net Price", "Sales Price", "Quantity"
            }
        ));
        ItemTable.setShowGrid(true);
        ItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ItemTable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel3.setText("Search Item");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel4.setText("Supplier ID");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel5.setText("Net Price");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel6.setText("Sales Price");

        BackToMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackToMenuBtn.setLabel("MENU");
        BackToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuBtnActionPerformed(evt);
            }
        });

        txtSalesPrice.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txtSalesPrice.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        txtItemPrice.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        txtItemName.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        txtItemId.setBackground(new java.awt.Color(255, 255, 204));
        txtItemId.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        selectSupplierbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        selectSupplierbtn.setText("Select Suppliers");
        selectSupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSupplierbtnActionPerformed(evt);
            }
        });

        txtSupplierid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txtSupplierid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSupplierid.setEnabled(false);

        searchBtn.setBackground(java.awt.SystemColor.activeCaption);
        searchBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchBtn.setForeground(java.awt.SystemColor.controlLtHighlight);
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        editBtn.setText("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BackToMenuBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtSalesPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtItemPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtItemName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtItemId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(selectSupplierbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtSupplierid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(searchBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(addBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(saveBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(editBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(deleteBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(BackToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(183, 183, 183)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, 0)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addComponent(txtSupplierid)
                                            .addGap(18, 18, 18)
                                            .addComponent(selectSupplierbtn))))
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(BackToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSupplierbtn)
                    .addComponent(txtSupplierid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(saveBtn))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn))
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    private void BackToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuBtnActionPerformed
        // TODO add your handling code here:
        SalesManagerMenu menu = new SalesManagerMenu();
        menu.setLocationRelativeTo(null); //center the window
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackToMenuBtnActionPerformed

    private void ItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemTableMouseClicked
        //TODO add your handling code here:
        int selectedRow = ItemTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) ItemTable.getModel();
        if(selectedRow != -1){
            txtItemId.setText(model.getValueAt(selectedRow, 0).toString()+ " - " + model.getValueAt(selectedRow, 1).toString());
            txtItemName.setText(model.getValueAt(selectedRow, 1).toString());
            txtSupplierid.setText(model.getValueAt(selectedRow, 2).toString());
            txtItemPrice.setText(model.getValueAt(selectedRow, 3).toString());
            txtSalesPrice.setText(model.getValueAt(selectedRow, 4).toString());
            setUnenabled();  
        }   
    }//GEN-LAST:event_ItemTableMouseClicked

    private void selectSupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSupplierbtnActionPerformed
        // TODO add your handling code here:
        JPanel Supplierpanel = new JPanel();
        Supplierpanel.setLayout(new BoxLayout(Supplierpanel, BoxLayout.Y_AXIS));

        ArrayList<JCheckBox> checkBoxes = new ArrayList<>();
        String[] selectedIds = txtSupplierid.getText().split(" | ");
        for (Supplier supplier : supplierList) {
            String supplierId = supplier.getSupplierId();
            String label = supplierId + " - " + supplier.getSupplierName();
            JCheckBox checkBox = new JCheckBox(label);
            // Pre-select if supplier ID exists
            for (String id : selectedIds) {
                if (supplierId.equalsIgnoreCase(id.trim())) {
                    checkBox.setSelected(true);
                    break;
                }
            }
            Supplierpanel.add(checkBox);
            checkBoxes.add(checkBox);
        }

        
        JScrollPane scrollPane = new JScrollPane(Supplierpanel);
        scrollPane.setPreferredSize(new Dimension(250,200));
        
        int result = JOptionPane.showConfirmDialog(
            null, 
            scrollPane, 
            "Select Suppliers",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION){
            ArrayList<String> selectedSupplierIds = new ArrayList<>();
            for(JCheckBox cb : checkBoxes){
                if(cb.isSelected()){
                    String supplierId = cb.getText().split(" - ")[0].trim();
                    selectedSupplierIds.add(supplierId);
                }
            }
            if (!selectedSupplierIds.isEmpty()) {
                txtSupplierid.setText(String.join(", ", selectedSupplierIds));
            } else {
                txtSupplierid.setText("");
                JOptionPane.showMessageDialog(null, "No suppliers selected.");
            }   
        }
    }//GEN-LAST:event_selectSupplierbtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String findID = txtItemId.getText().trim();
        if(findID.isEmpty()){
            JOptionPane.showMessageDialog(this, "❌ Please enter Item ID or Name to search.");
            return;//exit the method here
        }
        DefaultTableModel model = (DefaultTableModel)ItemTable.getModel();
        boolean found = false;
        for(int i=0; i<model.getRowCount();i++){
            if(model.getValueAt(i,0).toString().equalsIgnoreCase(findID)||model.getValueAt(i,1).toString().equalsIgnoreCase(findID)){
                txtItemId.setText(model.getValueAt(i, 0).toString() +" - " +model.getValueAt(i, 1).toString() );
                txtItemName.setText(model.getValueAt(i, 1).toString());
                txtSupplierid.setText(model.getValueAt(i, 2).toString());
                txtItemPrice.setText(model.getValueAt(i, 3).toString());
                txtSalesPrice.setText(model.getValueAt(i, 4).toString());
                ItemTable.setRowSelectionInterval(i,i);
                found = true;
                setUnenabled();
                break; 
            }
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "❌ Item not found.");
            clearInput();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try{
            if (txtItemName.getText().isEmpty() ||
                txtSupplierid.getText().isEmpty()||
                txtItemPrice.getText().isEmpty() ||
                txtSalesPrice.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields.");
                return; // stop the method here
            }
            //check item id
            String newItemId = generateNextItemID();
            boolean isDuplicate = false;
            for (Item item : itemList){
                if (item.getItemName().equalsIgnoreCase(txtItemName.getText())) {
                    isDuplicate = true;
                    break;
                }
            }
            if(isDuplicate){
                JOptionPane.showMessageDialog(this, "Item already exists. Please use a different ID.");
                return;
            }
            
            String itemName = txtItemName.getText().trim();
            double netPrice = Double.parseDouble(txtItemPrice.getText().trim());
            double SalesPrice = Double.parseDouble(txtSalesPrice.getText().trim());
            int quantity = 0;
            String[] supplierIds = txtSupplierid.getText().split(",");
            
            List<Supplier> matchedSuppliers = new ArrayList<>();
            for (String sid : supplierIds){
                for (Supplier s : this.supplierList){
                    if (s.getSupplierId().equalsIgnoreCase(sid.trim())){
                        matchedSuppliers.add(s);
                        break;
                    }
                }
            }

            Item newItem = new Item(newItemId, itemName, matchedSuppliers, netPrice, SalesPrice, quantity);            
            itemList.add(newItem);
            FileWriterUtil.writeFile("item.txt",Item.convertToStringArrayList(itemList));
            JOptionPane.showMessageDialog(this, "New Item added successfully");
            System.out.println("New item added.");
            //clear input
            clearInput();
            loadItemtoTable();
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Price and Quantity must be numeric.");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try{
            String itemId = txtItemId.getText().split(" - ")[0];
            if (itemId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Item ID is missing.");
                return;
            }
            if (txtItemName.getText().isEmpty() ||txtSupplierid.getText().isEmpty() ||txtItemPrice.getText().isEmpty() ||txtSalesPrice.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields.");
                return;
            }
            String[] supplierId = txtSupplierid.getText().split(",");
            ArrayList<Supplier> matchedSupplierIds = new ArrayList<>();
            for(String id : supplierId){
                String trimmedId = id.trim();
                for (Supplier s : supplierList) {
                    if (s.getSupplierId().equalsIgnoreCase(trimmedId)) {
                        matchedSupplierIds.add(s);
                        break;
                    }
                }
            }
            if(matchedSupplierIds.isEmpty()){
                JOptionPane.showMessageDialog(this,"Supplier ID(s) not found.");
                return;
            }
            boolean found = false;
            for(Item item : itemList){
                if(item.getItemID().equalsIgnoreCase(itemId)){
                    item.setItemName(txtItemName.getText().trim());
                    item.setPrice(Double.parseDouble(txtItemPrice.getText().trim()));
                    item.setSalesPrice(Double.parseDouble(txtSalesPrice.getText().trim()));                   
                    item.getSupplier().clear();
                    for(Supplier s : matchedSupplierIds){
                        item.getSupplier().add(s);
                    }
                    found = true;
                    break;
                }
            }
            if(!found){
                JOptionPane.showMessageDialog(this, "Item not found in the list.");
                return;
            }
            FileWriterUtil.writeFile("item.txt",Item.convertToStringArrayList(itemList));
            JOptionPane.showMessageDialog(this, "Item updated Successfully");
            clearInput();
            loadItemtoTable();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Price and Quantity must be numeric");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        String editID = txtItemId.getText().trim();
        DefaultTableModel model = (DefaultTableModel)ItemTable.getModel();
        boolean found = false;
        for(int i=0; i<model.getRowCount();i++){
            if(model.getValueAt(i,0).toString().equalsIgnoreCase(editID)){
                txtItemName.setText(model.getValueAt(i, 1).toString());
                txtSupplierid.setText(model.getValueAt(i, 2).toString());
                txtItemPrice.setText(model.getValueAt(i, 3).toString());
                txtSalesPrice.setText(model.getValueAt(i, 4).toString());
                ItemTable.setRowSelectionInterval(i,i);
                found = true;
                break; 
            }
        }
        setEnabled();
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String itemNameToDelete = txtItemName.getText();
        int comfirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this item?","Confirm Delete", JOptionPane.YES_NO_OPTION);
        if(comfirm == JOptionPane.YES_OPTION){
            boolean removed = false;
            for (int j = 0; j<itemList.size(); j++){
                Item i = itemList.get(j); 
                if(i.getItemName().equalsIgnoreCase(itemNameToDelete)){
                    itemList.remove(j);
                    removed = true;
                    break;
                }
            }
            if(removed){
                FileWriterUtil.writeFile("item.txt",Item.convertToStringArrayList(itemList));
                loadItemtoTable();
                JOptionPane.showMessageDialog(this, "Item deleted successfully.");
            }else{
                JOptionPane.showMessageDialog(this, "Item not found in list.");
            }
        }
        clearInput();
        setEnabled();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearInput();
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void makeTableReadOnly(){
        DefaultTableModel model = new DefaultTableModel(
        new String[]{"Item ID","Item Name", "Supplier ID", "Net Price", "Sales Price","Quantity"},0
        ){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        ItemTable.setModel(model);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        for (int i = 0; i < ItemTable.getColumnCount(); i++) {
            ItemTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    
    private String generateNextItemID(){
        int maxId = 0;
        for (Item item : itemList) {
            String id = item.getItemID();
            if (id.matches("I\\d+")) {
                int num = Integer.parseInt(id.substring(1));
                if (num > maxId) {
                    maxId = num;
                }
            }
        }
        return String.format("I%03d", maxId + 1);
    }
    
    private void clearInput(){
        txtItemId.setText("");
        txtSupplierid.setText("");
        txtItemName.setText("");
        txtItemPrice.setText("");
        txtSalesPrice.setText("");
    }
    
    private void setEnabled(){
        txtItemName.setEditable(true);
        txtItemName.setBackground(Color.WHITE);
        selectSupplierbtn.setEnabled(true);
        txtSupplierid.setBackground(Color.WHITE);
        txtItemPrice.setEditable(true);
        txtItemPrice.setBackground(Color.WHITE);
        txtSalesPrice.setEditable(true);
        txtSalesPrice.setBackground(Color.WHITE);
    }
    
     private void setUnenabled(){
        txtItemName.setEditable(false);
        txtItemName.setBackground(new Color(250, 250, 250));
        selectSupplierbtn.setEnabled(false);
        txtSupplierid.setBackground(new Color(250, 250, 250));
        txtItemPrice.setEditable(false);
        txtItemPrice.setBackground(new Color(250, 250, 250));
        txtSalesPrice.setEditable(false);
        txtSalesPrice.setBackground(new Color(250, 250, 250));
    }
    
    private void loadItemtoTable(){
        DefaultTableModel model = (DefaultTableModel) ItemTable.getModel();
        model.setRowCount(0);
        for (Item item : itemList) {
            Object[] row = {
                item.getItemID(),
                item.getItemName(),
                String.join(" | ", item.getSupplierids()),
                item.getPrice(),
                item.getSalesPrice(),
                item.getStock(),
            };
            model.addRow(row);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BackToMenuBtn;
    private javax.swing.JTable ItemTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectSupplierbtn;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtSalesPrice;
    private javax.swing.JTextField txtSupplierid;
    // End of variables declaration//GEN-END:variables
}
